# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/reference/configuration

[environments.local]
url = "jdbc:postgresql://localhost:5552/db"
user = "user"
password = "password"
# driver =
# schemas =
# connectRetries =
# connectRetriesInterval =
# initSql =
# jdbcProperties =
# resolvers =

[flyway]
environment = "local" # It is recommended to configure environment as a commandline argument. This allows using different environments depending on the caller.
locations = ["filesystem:migrations"]
# jarDirs = ["path/to/java/migrations"]

# [environments.build]
# url = "jdbc:sqlite::memory:"
# user = "buildUser"
# password = "buildPassword"

# [flyway.check]
# buildEnvironment = "build"